name: html_builder_vdom
version: 0.0.0
description: Render an html_builder AST into a diffed HTML tree.
author: Tobe O <thosakwe@gmail.com>
dependencies:
  html_builder: ^1.0.1
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.0
  test: ^0.12.0
dev_transformers:
  - dart_to_js_script_rewriter